import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
import { corsHeaders } from "./cors.ts";
export function client(req: Request) { const auth = req.headers.get("Authorization") || ""; return createClient(Deno.env.get("SUPABASE_URL")!, Deno.env.get("SUPABASE_ANON_KEY")!, { global: { headers: { Authorization: auth } } }); }
export function admin() { return createClient(Deno.env.get("SUPABASE_URL")!, Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!); }
export async function user(req: Request) { const { data, error } = await client(req).auth.getUser(); if (error || !data.user) throw new Error("AUTH_REQUIRED"); return data.user; }
export function json(value: unknown, status = 200) { return new Response(JSON.stringify(value), { status, headers: { ...corsHeaders, "Content-Type": "application/json" } }); }
export async function body(req: Request) { return await req.json() as Record<string, unknown>; }
export function env(name: string) { const value = Deno.env.get(name); if (!value) throw new Error(`${name}_NOT_CONFIGURED`); return value; }
export async function rateLimit(userId:string,feature:string,limit=20){const {data,error}=await admin().rpc("check_rate_limit",{p_user_id:userId,p_feature:feature,p_limit:limit});if(error)throw error;if(!data)throw new Error("RATE_LIMITED");}
export async function reserve(req: Request, feature: string, model: string, _baseCredits: number, requestId: string, inputChars: number) { const u = await user(req); const db=admin(); await rateLimit(u.id,feature); const {data:existing}=await db.from("usage_ledger").select("id").eq("request_id",requestId).maybeSingle(); if(existing)throw new Error("REQUEST_ALREADY_PROCESSED"); const [{data:catalog,error:modelError},{data:entitlement}]=await Promise.all([db.from("model_catalog").select("enabled,available_features,free_enabled,pro_enabled").eq("model_id",model).single(),db.from("user_entitlements").select("period_end,status,plans(name)").eq("user_id",u.id).maybeSingle()]); if(modelError||!catalog?.enabled)throw new Error("MODEL_DISABLED"); const isPro=(entitlement as any)?.plans?.name==="pro"&&(entitlement as any)?.status==="active"&&new Date((entitlement as any)?.period_end||0)>new Date(); if(!(isPro?catalog.pro_enabled:catalog.free_enabled))throw new Error("MODEL_PLAN_RESTRICTED"); const category=feature.startsWith("summary_")?"summary":feature==="figure_explain"||feature==="table_extract"?"visual":feature==="brainstorm"?"chat":feature; if(!catalog.available_features?.includes(category))throw new Error("MODEL_DISABLED"); const { data, error } = await db.rpc("consume_credits", { p_user_id:u.id,p_feature:feature,p_model:model,p_credits:2,p_request_id:requestId,p_input_chars:inputChars }); if (error) throw error; if (!data?.ok) throw new Error("QUOTA_EXCEEDED"); return { u, db, credits: isPro?0:2, remaining: data.creditsRemaining, isPro }; }
export async function settle(requestId:string,outputChars:number){const {error}=await admin().rpc("complete_usage",{p_request_id:requestId,p_output_chars:outputChars});if(error)throw error;}
export async function refund(requestId:string,errorCode:string){if(!requestId)return;await admin().rpc("refund_credits",{p_request_id:requestId,p_error_code:errorCode.slice(0,200)});}
