import { useEffect, useState } from "react";
import { ArrowRight, Brain, Check, ChevronDown, Download, ExternalLink, FileText, FolderKanban, Highlighter, MessageSquareText, MonitorDown, Palette, Presentation, ScanSearch, Sparkles, Wrench } from "lucide-react";
import "./about.css";

declare const __SHIDEA_EXTENSION_VERSION__: string;
declare const __SHIDEA_RELEASE_DATE__: string;
const downloadUrl = "/downloads/shidea-edge-extension.zip";
const releasesUrl = "https://github.com/Michael8023/inkwise-web/releases";

function ReaderPreview() { return <div className="product-preview reader-preview"><div className="preview-bar"><i/>Attention Is All You Need.pdf <span/>第 6 / 15 页</div><div className="reader-body"><aside><FileText size={15}/><b/><b className="active"/><b/></aside><article><small>3.2 &nbsp; Model Architecture</small><h3>Attention mechanisms enable models to focus on relevant context.</h3><p>We propose a new simple network architecture, the Transformer, based solely on attention mechanisms.</p><mark>Attention allows the model to reason across the full sequence.</mark><p>The architecture is more parallelizable and requires less time to train.</p></article><section><div><strong>AI 助手</strong><span>笔记</span></div><p><Sparkles size={12}/> AI 摘要</p><b>这篇论文提出了什么？</b><small>用注意力机制替代循环结构，让长距离依赖建模更直接。</small><em>继续追问… <ArrowRight size={12}/></em></section></div></div>; }
function WorkspacePreview() { return <div className="product-preview workspace-preview"><div className="preview-bar"><img src="/brand/shidea-mark.png" alt=""/><b>识谛</b> 文献工作台 <span/><em>搜索标题、文件名或来源</em></div><div className="workspace-body"><aside><small>我的空间</small><b className="active"><FolderKanban size={14}/>全部文献</b><b><FileText size={14}/>深度学习</b><b><FileText size={14}/>待读</b></aside><main><div className="research-thread"><div><small>RESEARCH THREAD</small><h3>我的工作概述</h3><p>探索高效、可信的多模态学习系统。</p></div><button>编辑</button></div><Paper title="Attention Is All You Need" state="已阅读"/><Paper title="Learning Transferable Visual Models" state="待读"/></main></div></div>; }
function Paper({ title, state }: { title: string; state: string }) { return <div className="paper-row"><FileText size={17}/><div><b>{title}</b><small>15 页 · 2026.08.17</small></div><span>{state}</span></div>; }
function BrainstormPreview() { return <div className="product-preview brainstorm-preview"><div className="preview-bar"><img src="/brand/shidea-mark.png" alt=""/><b>识谛 · 阅读空间</b><span/>Brainstorm</div><div className="brainstorm-body"><article><small>当前阅读文献</small><h3>Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks</h3><p>在阅读过程中，将这篇论文与个人研究主线和文献库相连接。</p></article><aside><small><Brain size={13}/> RESEARCH BRAINSTORM</small><h3>从文献到你的下一步</h3><section><b>当前研究主线</b><p>面向复杂文献的可信 AI 辅助研究工作流。</p></section><section><b>本次参考文献</b><p>✓ 当前阅读文献</p><p>□ 另选 2 篇文献库论文</p></section><button><Brain size={14}/>生成研究启发</button></aside></div></div>; }
function PptPreview() { return <div className="product-preview ppt-flow-preview"><div className="preview-bar"><img src="/brand/shidea-mark.png" alt=""/><b>识谛 · AI PPT 任务中心</b><span/>任务进行中</div><div className="ppt-flow-body"><div className="ppt-flow-source"><FileText size={22}/><b>论文 PDF</b><small>已入库 · 18 页</small></div><ArrowRight size={18}/><div className="ppt-flow-task"><span>制作要求</span><b>组会汇报，突出方法与结果</b><i>大纲 · 模板 · 自定义模板</i></div><ArrowRight size={18}/><div className="ppt-flow-output"><Presentation size={23}/><b>汇报 PPT</b><small>生成并下载</small></div></div></div>; }
const installSteps = { edge: ["下载并解压识谛插件 ZIP 安装包。", "在地址栏打开 edge://extensions，并开启“开发人员模式”。", "选择“加载解压缩的扩展”，选中解压后的文件夹。", "在工具栏固定“识谛”，即可从任意 PDF 开始阅读。"], chrome: ["下载并解压识谛插件 ZIP 安装包。", "在地址栏打开 chrome://extensions，并开启“开发者模式”。", "点击“加载已解压的扩展程序”，选中解压后的文件夹。", "在工具栏固定“识谛”，即可从任意 PDF 开始阅读。"] };

export function AboutPage() {
  const [browser, setBrowser] = useState<"edge" | "chrome">("edge"), [menu, setMenu] = useState(false);
  useEffect(() => {
    document.title = "识谛 shidea｜AI 驱动的研究阅读空间";
    document.body.classList.add("about-active");
    window.scrollTo(0, 0);
    const targets = Array.from(document.querySelectorAll<HTMLElement>(".about-page .section, .about-page .showcase, .about-page .closing"));
    targets.forEach(target => target.classList.add("about-reveal"));
    const observer = new IntersectionObserver(entries => entries.forEach(entry => {
      if (entry.isIntersecting) { entry.target.classList.add("is-visible"); observer.unobserve(entry.target); }
    }), { threshold: 0.12 });
    targets.forEach(target => observer.observe(target));
    return () => { observer.disconnect(); document.body.classList.remove("about-active"); document.title = "识谛 shidea"; };
  }, []);
  const date = new Intl.DateTimeFormat("zh-CN", { dateStyle: "long" }).format(new Date(__SHIDEA_RELEASE_DATE__)); const browserUrl = browser === "edge" ? "edge://extensions" : "chrome://extensions";
  return <main className="about-page"><header className="about-nav"><a className="about-brand" href="/"><img src="/brand/shidea-mark.png" alt="识谛"/>识谛 <em>shidea</em></a><button className="about-menu" aria-label="展开导航" onClick={() => setMenu(!menu)}><ChevronDown size={18}/></button><nav className={menu ? "open" : ""}><a href="#capabilities">产品能力</a><a href="#ppt">AI PPT</a><a href="#plans">产品方案</a><a href="#install">安装教程</a><a href="#start">使用方式</a></nav><div className="nav-actions"><a href="/">打开识谛</a><a href={downloadUrl} download><Download size={14}/>下载插件</a></div></header>
    <section className="about-hero"><div><p className="eyebrow">SHIDEA · AI RESEARCH WORKFLOW</p><h1>从读论文，到<br/><span>产出研究成果。</span></h1><p className="lede">识谛把 AI 阅读、图文解析、文献管理、研究推演与 PPT 汇报放进同一个工作空间。每一次理解，都能自然走向下一步产出。</p><div className="actions"><a className="button primary" href="/">打开识谛 <ArrowRight size={17}/></a><a className="button" href={downloadUrl} download><Download size={16}/>下载 Edge / Chrome 插件</a></div><small className="release-note">插件 v{__SHIDEA_EXTENSION_VERSION__} · ZIP 安装包 · 更新于 {date}</small></div><div className="hero-visual"><ReaderPreview/></div></section>
    <section className="proof"><span>读懂一篇文献</span><span>建立研究脉络</span><span>完成一次汇报</span></section>
    <section id="capabilities" className="section capabilities"><div className="heading"><p className="eyebrow">ONE PLACE, FULL WORKFLOW</p><h2>从理解，到组织，<br/>再到研究产出。</h2><p>不再在 PDF、聊天窗口、文件夹与演示软件间来回切换。识谛让研究信息保持连通。</p></div><div className="feature-grid workflow-grid"><article className="feature-card wide"><div className="icon"><Highlighter size={18}/></div><h3>AI 阅读，留在原文旁</h3><p>摘要、全文问答、划词解释、高亮与笔记都在 PDF 阅读器中完成。</p><ReaderPreview/></article><article className="feature-card"><div className="icon"><ScanSearch size={18}/></div><h3>图文解析，按需开启</h3><p>截图框选图像、表格或公式交给 AI 解读；需要时再启用版面识别，自动定位页面结构。</p><div className="diagram"><div/><span>Figure 2 · Formula</span><b>截图解析</b></div></article><article className="feature-card"><div className="icon"><Wrench size={18}/></div><h3>科研工具箱</h3><p>从论文图表截图中提取常用 RGB 配色，将视觉素材转成可复用的研究资源。</p><div className="tool-palette-preview"><Palette size={23}/><span/><span/><span/><b>提取科研配色</b></div></article></div></section>
    <section className="showcase"><div className="showcase-copy"><p className="eyebrow">YOUR RESEARCH, CONNECTED</p><h2>把文献库变成<br/>自己的研究脉络。</h2><p>在文献工作台中组织资料、维护多层文件夹与标签；用“我的工作概述”定义研究主线，让每一次分析都贴合你正在推进的问题。</p><a href="/">进入文献工作台 <ArrowRight size={16}/></a></div><WorkspacePreview/></section>
    <section className="showcase reverse"><BrainstormPreview/><div className="showcase-copy"><p className="eyebrow">BRAINSTORM WITH EVIDENCE</p><h2>让多篇文献，<br/>回应你的工作。</h2><p>Brainstorm 会结合当前论文、最多五篇文献库资料和个人研究主线，提炼可借鉴的思路，并清楚区分论文证据与有待验证的推断。</p><a href="/">开始一次 Brainstorm <ArrowRight size={16}/></a></div></section>
    <section id="ppt" className="showcase ppt-showcase"><div className="showcase-copy"><p className="eyebrow">AI PPT, FROM YOUR PAPERS</p><h2>从一篇 PDF，<br/>走到一次清晰汇报。</h2><p>在文献工作台选择已入库 PDF，写下制作要求，即可进入 AI PPT 任务中心；继续修改大纲、选择模板或上传自定义模板，生成后下载演示文稿。</p><a href="/">打开 AI PPT 任务中心 <ArrowRight size={16}/></a></div><PptPreview/></section>
    <section id="plans" className="section plans"><div className="heading centered"><p className="eyebrow">SIMPLE, TRANSPARENT ACCESS</p><h2>选择适合你的方式。</h2><p>从一篇论文开始；需要持续、深度的 AI 协作时，再升级你的工作空间。</p></div><div className="plan-grid"><article><p>FREE</p><h3>按需探索</h3><b>¥1 <small>= 50 积分</small></b><ul><li><Check size={15}/>每次 AI 调用 2 积分</li><li><Check size={15}/>完整 PDF 阅读与文献工作台</li><li><Check size={15}/>可见全部模型权限</li></ul><a href="/">打开识谛</a></article><article className="pro"><p>PRO · 30 DAYS</p><h3>专注深入研究</h3><b>¥30 <small>/ 30 天</small></b><ul><li><Check size={15}/>无限制 AI 使用，不扣积分</li><li><Check size={15}/>解锁 Pro 可用模型</li><li><Check size={15}/>单次购买，到期恢复 Free</li></ul><a href="/">开始 Pro 体验 <ArrowRight size={15}/></a></article></div></section>
    <section id="install" className="section install"><div className="heading"><p className="eyebrow">GET STARTED IN MINUTES</p><h2>安装插件，<br/>把识谛带到身边。</h2><p>当前支持 Microsoft Edge 和 Google Chrome。下载安装包后，通过浏览器开发者模式加载即可使用。</p><div className="download-card"><MonitorDown size={20}/><div><b>识谛浏览器插件 v{__SHIDEA_EXTENSION_VERSION__}</b><small>ZIP · 更新于 {date}</small></div><a href={downloadUrl} download>下载 <Download size={14}/></a></div><a className="history" href={releasesUrl} target="_blank" rel="noreferrer">查看 GitHub Releases 与历史版本 <ExternalLink size={12}/></a></div><div className="install-card"><div className="tabs"><button className={browser === "edge" ? "active" : ""} onClick={() => setBrowser("edge")}>Microsoft Edge</button><button className={browser === "chrome" ? "active" : ""} onClick={() => setBrowser("chrome")}>Google Chrome</button></div><ol>{installSteps[browser].map((step, index) => <li key={step}><b>{String(index + 1).padStart(2,"0")}</b>{step}</li>)}</ol><a className="button compact" href={browserUrl}><ExternalLink size={14}/>打开 {browserUrl}</a><p>其他浏览器暂未适配。加载后若未显示图标，请在扩展菜单中将“识谛”固定到工具栏。</p></div></section>
    <section id="start" className="section start"><div><p className="eyebrow">A QUIET START</p><h2>从一篇论文，<br/>开始你的工作流。</h2></div><ol>{[["打开识谛并登录","创建你的个人阅读与研究空间。"],["导入本地 PDF 或 DOI","让论文回到可以专注阅读的界面。"],["摘要、提问与标记重点","在原文上下文中获得 AI 的即时支持。"],["沉淀到工作台，继续 Brainstorm","将阅读转化为下一步可执行的研究启发。"]].map(([title,text], i) => <li key={title}><span>0{i+1}</span><div><b>{title}</b><p>{text}</p></div></li>)}</ol></section>
    <section className="closing"><p className="eyebrow">SHIDEA · YOUR READING SPACE</p><h2>每一次阅读，<br/>都值得通向更清晰的思考。</h2><div className="actions"><a className="button primary" href="/">打开识谛 <ArrowRight size={17}/></a><a className="button" href={downloadUrl} download>下载插件 <Download size={16}/></a></div></section><footer><a className="about-brand" href="/"><img src="/brand/shidea-mark.png" alt=""/>识谛 <em>shidea</em></a><span>AI 驱动的研究阅读空间</span><a href={releasesUrl} target="_blank" rel="noreferrer">GitHub Releases <ExternalLink size={12}/></a></footer></main>;
}
