import { useEffect, useState } from "react";
import { createRoot } from "react-dom/client";
import { Download, KeyRound, LogOut, RefreshCw, ShieldCheck } from "lucide-react";
import { functionRequest, supabase, supabaseConfigured } from "./api";
import "./redemption-admin.css";

type Batch = { label: string; productCode: string; createdAt: string; total: number; redeemed: number };
const productLabels: Record<string, string> = { "points-50": "50 积分 · ¥1", "points-250": "250 积分 · ¥5", "points-500": "500 积分 · ¥10", "pro-month": "Pro 月卡 · 30 天" };
const errors: Record<string, string> = { ADMIN_REQUIRED: "当前账户没有兑换码管理权限。", AUTH_REQUIRED: "请先登录管理员账户。", INVALID_REDEMPTION_BATCH: "请选择商品，并输入 1 至 5,000 的生成数量。" };

function RedemptionAdmin() {
  const [session, setSession] = useState<any>(null), [checked, setChecked] = useState(false), [productCode, setProductCode] = useState("points-50"), [count, setCount] = useState("50"), [label, setLabel] = useState(""), [busy, setBusy] = useState(false), [message, setMessage] = useState(""), [batches, setBatches] = useState<Batch[]>([]);
  useEffect(() => { supabase.auth.getSession().then(({ data }) => { setSession(data.session); setChecked(true); }); const { data } = supabase.auth.onAuthStateChange((_e, next) => setSession(next)); return () => data.subscription.unsubscribe(); }, []);
  async function load() { if (!session) return; try { const response = await functionRequest("redemption-codes?admin=1"); const result = await response.json(); if (!response.ok) throw new Error(result.error); setBatches(result.batches || []); } catch (error) { const key = error instanceof Error ? error.message : ""; setMessage(errors[key] || "兑换码批次暂时无法读取。"); } }
  useEffect(() => { void load(); }, [session]);
  async function generate(event: React.FormEvent) { event.preventDefault(); setBusy(true); setMessage(""); try { const response = await functionRequest("redemption-codes", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "generate", productCode, count: Number(count), batchLabel: label }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error); const blob = new Blob([result.codes.join("\n") + "\n"], { type: "text/plain;charset=utf-8" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = `${result.productCode}-${result.batchLabel || "codes"}.txt`; link.click(); URL.revokeObjectURL(url); setMessage(`已生成 ${result.count} 枚兑换码，并下载 TXT。请立即导入链动小铺，不要将文件公开分享。`); setLabel(""); await load(); } catch (error) { const key = error instanceof Error ? error.message : ""; setMessage(errors[key] || "生成失败，请稍后重试。"); } finally { setBusy(false); } }
  if (!checked) return <div className="code-admin-loading">正在检查登录状态…</div>;
  if (!session) return <main className="code-admin-login"><section><KeyRound size={29}/><h1>兑换码管理</h1><p>请使用管理员账户登录后继续。</p>{supabaseConfigured ? <a href="/?account=1">前往识谛登录</a> : <span>尚未配置 Supabase。</span>}</section></main>;
  return <main className="code-admin"><header><a href="/admin">识谛 <small>CONTROL</small></a><div>{session.user.email}<button onClick={() => supabase.auth.signOut()}><LogOut size={14}/>退出</button></div></header><section className="code-admin-wrap"><p>REDEMPTION INVENTORY</p><h1>生成并管理兑换码</h1><span>原始卡密只会在生成后下载一次；服务器仅保存不可逆哈希。</span><form onSubmit={generate}><label>权益商品<select value={productCode} onChange={event => setProductCode(event.target.value)}>{Object.entries(productLabels).map(([code, name]) => <option value={code} key={code}>{name}</option>)}</select></label><label>生成数量<input type="number" min="1" max="5000" value={count} onChange={event => setCount(event.target.value)} /></label><label>批次备注（可选）<input maxLength={80} placeholder="例如：链动小铺首批" value={label} onChange={event => setLabel(event.target.value)} /></label><button disabled={busy}>{busy ? <><RefreshCw className="code-spin" size={16}/>生成中…</> : <><Download size={16}/>生成并下载 TXT</>}</button></form>{message && <div className="code-message"><ShieldCheck size={16}/>{message}</div>}<section className="code-batches"><div><h2>最近批次</h2><button onClick={() => void load()}><RefreshCw size={14}/>刷新</button></div>{batches.length ? <table><thead><tr><th>批次</th><th>商品</th><th>总数</th><th>已兑换</th><th>创建时间</th></tr></thead><tbody>{batches.map((batch, index) => <tr key={`${batch.label}-${batch.createdAt}-${index}`}><td>{batch.label || "未命名批次"}</td><td>{productLabels[batch.productCode] || batch.productCode}</td><td>{batch.total}</td><td>{batch.redeemed}</td><td>{new Date(batch.createdAt).toLocaleString("zh-CN")}</td></tr>)}</tbody></table> : <p>还没有兑换码批次。</p>}</section></section></main>;
}
export function mountRedemptionAdmin() { createRoot(document.getElementById("root")!).render(<RedemptionAdmin />); }
